dist: trusty
sudo: required

language: c

cache:
  apt: true

compiler:
  - gcc-5
  - clang-3.6

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-5
    - clang-3.6

script:
  - cc --version
  - make && make test
